name: ⭐評分和評論
description: 評價您的遊玩體驗
title: "[評價或評論]: "
labels: ["評分和評論	"]
assignees: []
body:
  - type: markdown
    attributes:
      value: "### Add a title 添加子標題：樓上輸入您要評論與評價的主題"
      
  - type: dropdown
    id: rating
    attributes:
      label: 請選擇評分
      description: 請為您的遊玩體驗評分
      options:
        - ★★★★★ (5星)
        - ★★★★☆ (4星)
        - ★★★☆☆ (3星)
        - ★★☆☆☆ (2星)
        - ★☆☆☆☆ (1星)
    validations:
      required: true
      
  - type: textarea
    id: review
    attributes:
      label: 您的評論或心得
      placeholder: 請分享您的遊戲體驗、建議或感受...
    validations:
      required: false
