name: 評分和評論
description: 評價您的遊玩體驗
title: "[評分和評論]: "
labels: ["評分和評論"]
assignees: []
body:
  - type: dropdown
    id: rating
    attributes:
      label: 請選擇評分
      description: 選擇一個星級來評價您的體驗
      options:
        - ★★★★★ (5星)
        - ★★★★☆ (4星)
        - ★★★☆☆ (3星)
        - ★★☆☆☆ (2星)
        - ★☆☆☆☆ (1星)
    validations:
      required: true
      
  - type: textarea
    id: review
    attributes:
      label: 您的評論或心得(支持圖片拖曳到這裡)
      placeholder: 請分享您的遊戲體驗、印象深刻的部分...
    validations:
      required: true
